# 工作流的名称
name: Deploy Hugo Site to Pages

# 触发条件：当推送到 main 分支时运行
on:
  push:
    branches:
      - master  # 如果你的主分支是 master，请修改这里

# 允许这个工作流创建和批准一个由 GITHUB_TOKEN 生成的提交
permissions:
  contents: write

# 定义一个任务（job）
jobs:
  # 任务的ID
  build-deploy:
    # 运行此任务的操作系统
    runs-on: ubuntu-latest
    
    # 任务的步骤
    steps:
      # 第1步：检出你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # 如果你的主题是作为 submodule 添加的，这行很重要
          fetch-depth: 0    # 获取所有历史记录，以便 Hugo 能获取 lastmod 等信息

      # 第2步：安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest' # 或者指定一个版本，如 '0.125.4'
          extended: true # 你的主题很可能需要 extended 版本

      # 第3步：运行 hugo 命令来构建网站
      - name: Build with Hugo
        run: hugo

      # 第4步：提交 docs 文件夹并推送到仓库
      - name: Commit and Push docs
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs
          # 检查是否有文件变动，如果有才进行提交
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "GHA: Build and deploy site [skip ci]"
            git push
          else
            echo "No changes to deploy."
          fi
